# Generated by Django 3.1.6 on 2021-04-10 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_advertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('contact_number', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.RemoveField(
            model_name='slocation',
            name='l_id',
        ),
        migrations.RemoveField(
            model_name='slocation',
            name='l_key',
        ),
        migrations.AlterField(
            model_name='advertise',
            name='post_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
