# Generated by Django 3.1.6 on 2021-06-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210410_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='ad_detail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='ad_type',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='address',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='img_3',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='img_4',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='img_5',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='prefer_type',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='response_set',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='status',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='user_id',
            field=models.IntegerField(default=False),
        ),
    ]
