# Generated by Django 3.1.6 on 2021-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20210604_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='ad_catagory',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
