# Generated by Django 3.1.6 on 2021-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20210604_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
