# Generated by Django 3.1.6 on 2021-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20210604_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
