# Generated by Django 3.1.6 on 2021-06-04 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20210604_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='post_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
