# Generated by Django 3.1.6 on 2021-06-05 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_auto_20210605_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='post_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
