# Generated by Django 3.1.6 on 2021-03-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_id', models.IntegerField()),
                ('division', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('l_key', models.CharField(max_length=100)),
            ],
        ),
    ]
