# Generated by Django 3.1.6 on 2021-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=100)),
                ('ad_detail', models.TextField(max_length=100)),
                ('ad_catagory', models.CharField(max_length=100)),
                ('ad_type', models.CharField(max_length=100)),
                ('post_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('available', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('deposit_tk', models.CharField(max_length=100)),
                ('monthly_rent', models.CharField(max_length=100)),
                ('prefer_type', models.CharField(max_length=100)),
                ('response_set', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
