# Generated by Django 3.1.6 on 2021-06-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20210602_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='advertise',
            name='ad_detail',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='ad_catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.category'),
        ),
    ]
