# Generated by Django 3.1.6 on 2021-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20210604_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='user_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
