# Generated by Django 3.1.6 on 2021-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20210604_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='email',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
