# Generated by Django 3.1.6 on 2021-06-04 16:41

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20210604_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='available',
            field=models.CharField(default='YES', max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='post_date_time',
            field=models.DateTimeField(),
        ),
    ]
