# Generated by Django 3.1.6 on 2021-06-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20210604_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
