# Generated by Django 3.1.6 on 2021-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_auto_20210606_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='available',
            field=models.CharField(default='YES', max_length=100),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
